-- RLS verification for the fund-tracker schema.
-- Run in the Supabase SQL Editor AFTER applying the migration.
-- Everything runs inside a transaction and is rolled back — no data is left
-- behind. Each check raises "ok: ..." as a NOTICE; any failure aborts with
-- an assert/exception message.

begin;

do $$
declare
  v_owner  uuid := gen_random_uuid();
  v_collab uuid := gen_random_uuid();
  v_other  uuid := gen_random_uuid();
  v_fund   uuid;
  v_token  text;
  v_token2 text;
  v_token3 text;
  v_result uuid;
  v_tx_owner uuid;
  v_tx_collab uuid;
  n int;
begin
  ---------------------------------------------------------------------------
  -- Setup (as postgres): three auth users; the trigger must create profiles.
  ---------------------------------------------------------------------------
  insert into auth.users (id, email) values
    (v_owner,  'owner@test.local'),
    (v_collab, 'collab@test.local'),
    (v_other,  'other@test.local');

  assert (select count(*) from public.profiles
          where id in (v_owner, v_collab, v_other)) = 3,
    'FAIL: profile trigger did not create 3 profiles';
  raise notice 'ok: profile rows auto-created for new auth users';

  -- Adding a phone to an existing account must sync to the profile.
  update auth.users set phone = '966500000001' where id = v_owner;
  assert (select phone from public.profiles where id = v_owner) = '966500000001',
    'FAIL: phone change did not sync to profile';
  raise notice 'ok: auth phone changes sync to profiles';

  ---------------------------------------------------------------------------
  -- Owner creates a fund; trigger must add the owner membership.
  ---------------------------------------------------------------------------
  perform set_config('request.jwt.claims',
    json_build_object('sub', v_owner, 'role', 'authenticated')::text, true);
  set local role authenticated;

  insert into public.funds (name, owner_id)
  values ('Wedding fund', v_owner)
  returning id into v_fund;

  assert (select role from public.fund_members
          where fund_id = v_fund and user_id = v_owner) = 'owner',
    'FAIL: owner membership row was not created by trigger';
  assert (select count(*) from public.funds where id = v_fund) = 1,
    'FAIL: owner cannot see their own fund';
  raise notice 'ok: fund created, owner membership auto-created, owner can read fund';

  -- Owner logs a credit and an expense.
  insert into public.transactions (fund_id, created_by, type, amount, description)
  values (v_fund, v_owner, 'credit', 1000, 'initial funding')
  returning id into v_tx_owner;
  insert into public.transactions (fund_id, created_by, type, amount)
  values (v_fund, v_owner, 'expense', 200);

  assert (select balance from public.fund_balances where fund_id = v_fund) = 800,
    'FAIL: balance view wrong for owner';
  raise notice 'ok: owner can add credit + expense; balance view = 800';

  -- Owner creates a share link (token generated by column default).
  insert into public.fund_share_links (fund_id, created_by)
  values (v_fund, v_owner)
  returning token into v_token;
  assert length(v_token) >= 32, 'FAIL: token too short';
  raise notice 'ok: owner created share link with generated token';

  ---------------------------------------------------------------------------
  -- Stranger (not a member): must see nothing, must not write anything.
  ---------------------------------------------------------------------------
  reset role;
  perform set_config('request.jwt.claims',
    json_build_object('sub', v_collab, 'role', 'authenticated')::text, true);
  set local role authenticated;

  assert (select count(*) from public.funds) = 0,
    'FAIL: non-member can see the fund';
  assert (select count(*) from public.transactions) = 0,
    'FAIL: non-member can see transactions';
  assert (select count(*) from public.fund_share_links) = 0,
    'FAIL: non-member can see share links';
  raise notice 'ok: non-member sees no funds, transactions, or share links';

  begin
    insert into public.transactions (fund_id, created_by, type, amount)
    values (v_fund, v_collab, 'expense', 10);
    raise exception 'FAIL: non-member could insert an expense';
  exception when insufficient_privilege then
    raise notice 'ok: non-member cannot insert an expense';
  end;
  set local role authenticated;

  begin
    insert into public.fund_members (fund_id, user_id, role)
    values (v_fund, v_collab, 'collaborator');
    raise exception 'FAIL: user could insert their own membership directly';
  exception when insufficient_privilege then
    raise notice 'ok: memberships cannot be self-inserted directly';
  end;
  set local role authenticated;

  ---------------------------------------------------------------------------
  -- Redeem the share link → collaborator membership.
  ---------------------------------------------------------------------------
  select public.redeem_share_link(v_token) into v_result;
  assert v_result = v_fund, 'FAIL: redeem did not return the fund id';
  assert (select role from public.fund_members
          where fund_id = v_fund and user_id = v_collab) = 'collaborator',
    'FAIL: redeem did not create a collaborator membership';
  assert (select count(*) from public.funds where id = v_fund) = 1,
    'FAIL: collaborator cannot see the fund after joining';
  raise notice 'ok: share link redeemed, collaborator can now see the fund';

  -- Redeeming again is idempotent.
  select public.redeem_share_link(v_token) into v_result;
  reset role;
  assert (select use_count from public.fund_share_links where token = v_token) = 1,
    'FAIL: idempotent redeem incremented use_count';
  set local role authenticated;
  raise notice 'ok: second redeem is idempotent (use_count still 1)';

  ---------------------------------------------------------------------------
  -- Collaborator permissions on transactions.
  ---------------------------------------------------------------------------
  insert into public.transactions (fund_id, created_by, type, amount, description)
  values (v_fund, v_collab, 'expense', 50, 'supplies')
  returning id into v_tx_collab;
  assert (select balance from public.fund_balances where fund_id = v_fund) = 750,
    'FAIL: balance wrong after collaborator expense';
  raise notice 'ok: collaborator can add an expense; balance = 750';

  begin
    insert into public.transactions (fund_id, created_by, type, amount)
    values (v_fund, v_collab, 'credit', 500);
    raise exception 'FAIL: collaborator could insert a credit';
  exception when insufficient_privilege then
    raise notice 'ok: collaborator cannot insert a credit';
  end;
  set local role authenticated;

  update public.transactions set amount = 55 where id = v_tx_collab;
  get diagnostics n = row_count;
  assert n = 1, 'FAIL: collaborator cannot edit their own expense';
  raise notice 'ok: collaborator can edit their own expense';

  begin
    update public.transactions set type = 'credit' where id = v_tx_collab;
    raise exception 'FAIL: collaborator turned their expense into a credit';
  exception when insufficient_privilege then
    raise notice 'ok: collaborator cannot change their expense into a credit';
  end;
  set local role authenticated;

  update public.transactions set amount = 999 where id = v_tx_owner;
  get diagnostics n = row_count;
  assert n = 0, 'FAIL: collaborator edited the owner''s transaction';
  delete from public.transactions where id = v_tx_owner;
  get diagnostics n = row_count;
  assert n = 0, 'FAIL: collaborator deleted the owner''s transaction';
  raise notice 'ok: collaborator cannot edit or delete others'' transactions';

  ---------------------------------------------------------------------------
  -- Collaborator cannot manage the fund, links, or members.
  ---------------------------------------------------------------------------
  update public.funds set name = 'hacked' where id = v_fund;
  get diagnostics n = row_count;
  assert n = 0, 'FAIL: collaborator renamed the fund';
  delete from public.funds where id = v_fund;
  get diagnostics n = row_count;
  assert n = 0, 'FAIL: collaborator deleted the fund';
  assert (select count(*) from public.fund_share_links) = 0,
    'FAIL: collaborator can read share links';
  delete from public.fund_members where fund_id = v_fund and user_id = v_owner;
  get diagnostics n = row_count;
  assert n = 0, 'FAIL: collaborator removed the owner''s membership';
  raise notice 'ok: collaborator cannot rename/delete fund, read links, or remove members';

  ---------------------------------------------------------------------------
  -- Owner moderation: edit/delete the collaborator's transaction.
  ---------------------------------------------------------------------------
  reset role;
  perform set_config('request.jwt.claims',
    json_build_object('sub', v_owner, 'role', 'authenticated')::text, true);
  set local role authenticated;

  update public.transactions set amount = 60 where id = v_tx_collab;
  get diagnostics n = row_count;
  assert n = 1, 'FAIL: owner cannot edit collaborator''s transaction';
  delete from public.transactions where id = v_tx_collab;
  get diagnostics n = row_count;
  assert n = 1, 'FAIL: owner cannot delete collaborator''s transaction';
  raise notice 'ok: owner can edit and delete any transaction in the fund';

  -- Owner can remove the collaborator, but not the owner row.
  delete from public.fund_members where fund_id = v_fund and user_id = v_collab;
  get diagnostics n = row_count;
  assert n = 1, 'FAIL: owner cannot remove a collaborator';
  delete from public.fund_members where fund_id = v_fund and user_id = v_owner;
  get diagnostics n = row_count;
  assert n = 0, 'FAIL: owner membership row was deletable';
  raise notice 'ok: owner can remove collaborators but not the owner row';

  ---------------------------------------------------------------------------
  -- Invalid links: revoked, expired, maxed out.
  ---------------------------------------------------------------------------
  update public.fund_share_links set revoked = true where token = v_token;
  insert into public.fund_share_links (fund_id, created_by, expires_at)
  values (v_fund, v_owner, now() - interval '1 hour')
  returning token into v_token2;
  insert into public.fund_share_links (fund_id, created_by, max_uses)
  values (v_fund, v_owner, 1)
  returning token into v_token3;
  reset role;
  update public.fund_share_links set use_count = 1 where token = v_token3;

  perform set_config('request.jwt.claims',
    json_build_object('sub', v_other, 'role', 'authenticated')::text, true);
  set local role authenticated;

  begin
    perform public.redeem_share_link(v_token);
    raise exception 'FAIL: revoked link was redeemable';
  exception when raise_exception then
    if sqlerrm like 'FAIL:%' then raise; end if;
    raise notice 'ok: revoked link rejected';
  end;
  set local role authenticated;

  begin
    perform public.redeem_share_link(v_token2);
    raise exception 'FAIL: expired link was redeemable';
  exception when raise_exception then
    if sqlerrm like 'FAIL:%' then raise; end if;
    raise notice 'ok: expired link rejected';
  end;
  set local role authenticated;

  begin
    perform public.redeem_share_link(v_token3);
    raise exception 'FAIL: maxed-out link was redeemable';
  exception when raise_exception then
    if sqlerrm like 'FAIL:%' then raise; end if;
    raise notice 'ok: maxed-out link rejected';
  end;
  set local role authenticated;

  begin
    perform public.redeem_share_link('no-such-token');
    raise exception 'FAIL: bogus token was redeemable';
  exception when raise_exception then
    if sqlerrm like 'FAIL:%' then raise; end if;
    raise notice 'ok: unknown token rejected';
  end;
  set local role authenticated;

  assert (select count(*) from public.funds) = 0,
    'FAIL: user gained fund access from invalid links';
  raise notice 'ok: no access gained from invalid links';

  ---------------------------------------------------------------------------
  -- Anonymous: no table access at all (grants revoked), cannot redeem.
  ---------------------------------------------------------------------------
  reset role;
  perform set_config('request.jwt.claims', '', true);
  set local role anon;
  begin
    perform count(*) from public.funds;
    raise exception 'FAIL: anon can select funds';
  exception when insufficient_privilege then
    raise notice 'ok: anon has no access to funds';
  end;
  set local role anon;
  begin
    perform count(*) from public.transactions;
    raise exception 'FAIL: anon can select transactions';
  exception when insufficient_privilege then
    raise notice 'ok: anon has no access to transactions';
  end;
  set local role anon;
  begin
    perform public.redeem_share_link(v_token);
    raise exception 'FAIL: anon could call redeem_share_link';
  exception when insufficient_privilege then
    raise notice 'ok: anon cannot call redeem_share_link';
  end;

  reset role;
  raise notice '=== ALL RLS CHECKS PASSED ===';
end;
$$;

rollback;
